-- ----------------------------------------------------------------------------------------
-- MySQL Script generated by MySQL Workbench
-- MySQL Workbench Forward Engineering
-- Date: Sun Jun 27 20:21:11 2021
-- Model: Example_php_team    
-- Version: 1.0
-- Author: Gerrit Bohne, Dominik Neddermeyer, Lukas Faldung
-- ----------------------------------------------------------------------------------------

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DB_CWWS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DB_CWWS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_CWWS` DEFAULT CHARACTER SET utf8 ;
USE `DB_CWWS` ;

-- -----------------------------------------------------
-- Table `DB_CWWS`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_CWWS`.`User` (
  `User_id` INT NOT NULL AUTO_INCREMENT,
  `User_name` VARCHAR(45) NOT NULL,
  `User_password` VARCHAR(255) NOT NULL,
  `User_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`User_id`),
  UNIQUE INDEX `User_id_UNIQUE` (`User_id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_CWWS`.`Format`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_CWWS`.`Format` (
  `Format_id` INT NOT NULL AUTO_INCREMENT,
  `Format_height` VARCHAR(55) NOT NULL,
  `Format_width` VARCHAR(55) NOT NULL,
  `Format_length` VARCHAR(55) NOT NULL,
  `Format_volume` VARCHAR(55) NULL,
  PRIMARY KEY (`Format_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_CWWS`.`Properties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_CWWS`.`Properties` (
  `Properties_id` INT NOT NULL AUTO_INCREMENT,
  `Properties_name` VARCHAR(45) NOT NULL,
  `Properties_description` VARCHAR(45) NULL,
  PRIMARY KEY (`Properties_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_CWWS`.`Usage_statistics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_CWWS`.`Usage_statistics` (
  `Usage_statistics_id` INT NOT NULL AUTO_INCREMENT,
  `Usage_statistics_number_of_accesses` INT UNSIGNED NULL,
  `Usage_statistics_last_modified` DATETIME NULL,
  PRIMARY KEY (`Usage_statistics_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_CWWS`.`Storage_yard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_CWWS`.`Storage_yard` (
  `Storage_id` INT NOT NULL AUTO_INCREMENT,
  `Storage_picture` LONGBLOB NOT NULL,
  `Format_Format_id` INT NOT NULL,
  `Properties_Properties_id` INT NULL,
  `Usage_statistics_idUsage_statistics` INT NULL,
  PRIMARY KEY (`Storage_id`),
  UNIQUE INDEX `Storage_id_UNIQUE` (`Storage_id` ASC) ,
  INDEX `fk_Storage_yard_Format1_idx` (`Format_Format_id` ASC) ,
  INDEX `fk_Storage_yard_Properties1_idx` (`Properties_Properties_id` ASC) ,
  INDEX `fk_Storage_yard_Usage_statistics1_idx` (`Usage_statistics_idUsage_statistics` ASC) ,
  CONSTRAINT `fk_Storage_yard_Format1`
    FOREIGN KEY (`Format_Format_id`)
    REFERENCES `DB_CWWS`.`Format` (`Format_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Storage_yard_Properties1`
    FOREIGN KEY (`Properties_Properties_id`)
    REFERENCES `DB_CWWS`.`Properties` (`Properties_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Storage_yard_Usage_statistics1`
    FOREIGN KEY (`Usage_statistics_idUsage_statistics`)
    REFERENCES `DB_CWWS`.`Usage_statistics` (`Usage_statistics_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_CWWS`.`Articel_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_CWWS`.`Articel_group` (
  `Articel_group_id` INT NOT NULL AUTO_INCREMENT,
  `Articel_group_picture` LONGBLOB NULL,
  `Properties_Properties_id` INT NOT NULL,
  PRIMARY KEY (`Articel_group_id`),
  UNIQUE INDEX `Articel_id_UNIQUE` (`Articel_group_id` ASC) ,
  INDEX `fk_Articel_group_Properties1_idx` (`Properties_Properties_id` ASC) ,
  CONSTRAINT `fk_Articel_group_Properties1`
    FOREIGN KEY (`Properties_Properties_id`)
    REFERENCES `DB_CWWS`.`Properties` (`Properties_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_CWWS`.`Articel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_CWWS`.`Articel` (
  `Articel_id` INT NOT NULL AUTO_INCREMENT,
  `Articel_expiry` DATE NULL,
  `Articel_picture` LONGBLOB NOT NULL,
  `Articel_rotatable` TINYINT(1) NULL,
  `Articel_stackable` TINYINT(1) NULL,
  `Articel_group_Articel_group_id` INT NULL,
  `Usage_statistics_Usage_statistics_id` INT NULL,
  `Properties_Properties_id` INT NOT NULL,
  `Format_Format_id` INT NOT NULL,
  PRIMARY KEY (`Articel_id`),
  UNIQUE INDEX `Articel_id_UNIQUE` (`Articel_id` ASC) ,
  INDEX `fk_Articel_Articel_group1_idx` (`Articel_group_Articel_group_id` ASC) ,
  INDEX `fk_Articel_Properties1_idx` (`Properties_Properties_id` ASC) ,
  INDEX `fk_Articel_Format1_idx` (`Format_Format_id` ASC) ,
  INDEX `fk_Articel_Usage_statistics1_idx` (`Usage_statistics_Usage_statistics_id` ASC) ,
  CONSTRAINT `fk_Articel_Articel_group1`
    FOREIGN KEY (`Articel_group_Articel_group_id`)
    REFERENCES `DB_CWWS`.`Articel_group` (`Articel_group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articel_Properties1`
    FOREIGN KEY (`Properties_Properties_id`)
    REFERENCES `DB_CWWS`.`Properties` (`Properties_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articel_Format1`
    FOREIGN KEY (`Format_Format_id`)
    REFERENCES `DB_CWWS`.`Format` (`Format_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articel_Usage_statistics1`
    FOREIGN KEY (`Usage_statistics_Usage_statistics_id`)
    REFERENCES `DB_CWWS`.`Usage_statistics` (`Usage_statistics_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_CWWS`.`Substorage_yard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_CWWS`.`Substorage_yard` (
  `Substorage_id` INT NOT NULL AUTO_INCREMENT,
  `Substorage_quantity` INT NOT NULL,
  `Substorage_category` VARCHAR(45) NOT NULL,
  `Substorage_yard_picture` LONGBLOB NULL,
  `Properties_Properties_id` INT NULL,
  `Storage_yard_Storage_id` INT NOT NULL,
  PRIMARY KEY (`Substorage_id`),
  INDEX `fk_Substorage_yard_Storage_yard1_idx` (`Storage_yard_Storage_id` ASC) ,
  INDEX `fk_Substorage_yard_Properties1_idx` (`Properties_Properties_id` ASC) ,
  CONSTRAINT `fk_Substorage_yard_Storage_yard1`
    FOREIGN KEY (`Storage_yard_Storage_id`)
    REFERENCES `DB_CWWS`.`Storage_yard` (`Storage_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Substorage_yard_Properties1`
    FOREIGN KEY (`Properties_Properties_id`)
    REFERENCES `DB_CWWS`.`Properties` (`Properties_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_CWWS`.`Substorage_yard_fixed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_CWWS`.`Substorage_yard_fixed` (
  `Substorage_fixed_id` INT NOT NULL AUTO_INCREMENT,
  `Substorage_fixed_category` VARCHAR(45) NOT NULL,
  `Articel_Articel_id` INT NULL,
  `Properties_Properties_id` INT NULL,
  `Format_Format_id` INT NOT NULL,
  `Substorage_yard_Substorage_id` INT NOT NULL,
  PRIMARY KEY (`Substorage_fixed_id`),
  INDEX `fk_Substorage_yard_fixed_Format1_idx` (`Format_Format_id` ASC) ,
  INDEX `fk_Substorage_yard_fixed_Articel1_idx` (`Articel_Articel_id` ASC) ,
  INDEX `fk_Substorage_yard_fixed_Substorage_yard1_idx` (`Substorage_yard_Substorage_id` ASC) ,
  INDEX `fk_Substorage_yard_fixed_Properties1_idx` (`Properties_Properties_id` ASC) ,
  CONSTRAINT `fk_Substorage_yard_fixed_Format1`
    FOREIGN KEY (`Format_Format_id`)
    REFERENCES `DB_CWWS`.`Format` (`Format_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Substorage_yard_fixed_Articel1`
    FOREIGN KEY (`Articel_Articel_id`)
    REFERENCES `DB_CWWS`.`Articel` (`Articel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Substorage_yard_fixed_Substorage_yard1`
    FOREIGN KEY (`Substorage_yard_Substorage_id`)
    REFERENCES `DB_CWWS`.`Substorage_yard` (`Substorage_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Substorage_yard_fixed_Properties1`
    FOREIGN KEY (`Properties_Properties_id`)
    REFERENCES `DB_CWWS`.`Properties` (`Properties_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_CWWS`.`Substorage_yard_mobile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_CWWS`.`Substorage_yard_mobile` (
  `Substorage_mobile_id` INT NOT NULL AUTO_INCREMENT,
  `Substorage_mobile_cover` TINYINT(1) NOT NULL,
  `Substorage_yard_mobile_binding` TINYINT(1) NULL,
  `Substorage_mobile_category` VARCHAR(45) NOT NULL,
  `Substorage_yard_mobile_Substorage_mobile_id` INT NULL,
  `Properties_Properties_id` INT NULL,
  `Format_Format_id` INT NOT NULL,
  `Articel_Articel_id` INT NOT NULL,
  `Substorage_yard_fixed_Substorage_fixed_id` INT NOT NULL,
  PRIMARY KEY (`Substorage_mobile_id`),
  UNIQUE INDEX `Substorage_mobile_id_UNIQUE` (`Substorage_mobile_id` ASC) ,
  INDEX `fk_Substorage_yard_mobile_Substorage_yard_mobile1_idx` (`Substorage_yard_mobile_Substorage_mobile_id` ASC) ,
  INDEX `fk_Substorage_yard_mobile_Format1_idx` (`Format_Format_id` ASC) ,
  INDEX `fk_Substorage_yard_mobile_Articel1_idx` (`Articel_Articel_id` ASC) ,
  INDEX `fk_Substorage_yard_mobile_Substorage_yard_fixed1_idx` (`Substorage_yard_fixed_Substorage_fixed_id` ASC) ,
  INDEX `fk_Substorage_yard_mobile_Properties1_idx` (`Properties_Properties_id` ASC) ,
  CONSTRAINT `fk_Substorage_yard_mobile_Substorage_yard_mobile1`
    FOREIGN KEY (`Substorage_yard_mobile_Substorage_mobile_id`)
    REFERENCES `DB_CWWS`.`Substorage_yard_mobile` (`Substorage_mobile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Substorage_yard_mobile_Format1`
    FOREIGN KEY (`Format_Format_id`)
    REFERENCES `DB_CWWS`.`Format` (`Format_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Substorage_yard_mobile_Articel1`
    FOREIGN KEY (`Articel_Articel_id`)
    REFERENCES `DB_CWWS`.`Articel` (`Articel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Substorage_yard_mobile_Substorage_yard_fixed1`
    FOREIGN KEY (`Substorage_yard_fixed_Substorage_fixed_id`)
    REFERENCES `DB_CWWS`.`Substorage_yard_fixed` (`Substorage_fixed_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Substorage_yard_mobile_Properties1`
    FOREIGN KEY (`Properties_Properties_id`)
    REFERENCES `DB_CWWS`.`Properties` (`Properties_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_CWWS`.`Subarticel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_CWWS`.`Subarticel` (
  `Subarticel_id` INT NOT NULL AUTO_INCREMENT,
  `Subarticel_quantity` INT NULL,
  `Subarticel_binding` TINYINT(1) NULL,
  `Subarticel_extracted` TINYINT(1) NULL,
  `Subarticel_time_of_storage` DATE NULL,
  `Articel_Articel_id` INT NOT NULL,
  PRIMARY KEY (`Subarticel_id`),
  UNIQUE INDEX `Subarticel_id_UNIQUE` (`Subarticel_id` ASC) ,
  INDEX `fk_Subarticel_Articel1_idx` (`Articel_Articel_id` ASC) ,
  CONSTRAINT `fk_Subarticel_Articel1`
    FOREIGN KEY (`Articel_Articel_id`)
    REFERENCES `DB_CWWS`.`Articel` (`Articel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_CWWS`.`Aliase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_CWWS`.`Aliase` (
  `Aliase_1` VARCHAR(45) NOT NULL,
  `Articel_Articel_id` INT NOT NULL,
  PRIMARY KEY (`Aliase_1`),
  INDEX `fk_Aliase_Articel1_idx` (`Articel_Articel_id` ASC) ,
  CONSTRAINT `fk_Aliase_Articel1`
    FOREIGN KEY (`Articel_Articel_id`)
    REFERENCES `DB_CWWS`.`Articel` (`Articel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_CWWS`.`User_has_Storage_yard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_CWWS`.`User_has_Storage_yard` (
  `User_User_id` INT NOT NULL,
  `Storage_yard_Storage_id` INT NOT NULL,
  PRIMARY KEY (`User_User_id`, `Storage_yard_Storage_id`),
  INDEX `fk_User_has_Storage_yard_Storage_yard1_idx` (`Storage_yard_Storage_id` ASC) ,
  INDEX `fk_User_has_Storage_yard_User1_idx` (`User_User_id` ASC) ,
  CONSTRAINT `fk_User_has_Storage_yard_User1`
    FOREIGN KEY (`User_User_id`)
    REFERENCES `DB_CWWS`.`User` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Storage_yard_Storage_yard1`
    FOREIGN KEY (`Storage_yard_Storage_id`)
    REFERENCES `DB_CWWS`.`Storage_yard` (`Storage_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_CWWS`.`User_has_Articel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_CWWS`.`User_has_Articel` (
  `User_User_id` INT NOT NULL,
  `Articel_Articel_id` INT NOT NULL,
  PRIMARY KEY (`User_User_id`, `Articel_Articel_id`),
  INDEX `fk_User_has_Articel_Articel1_idx` (`Articel_Articel_id` ASC) ,
  INDEX `fk_User_has_Articel_User1_idx` (`User_User_id` ASC) ,
  CONSTRAINT `fk_User_has_Articel_User1`
    FOREIGN KEY (`User_User_id`)
    REFERENCES `DB_CWWS`.`User` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Articel_Articel1`
    FOREIGN KEY (`Articel_Articel_id`)
    REFERENCES `DB_CWWS`.`Articel` (`Articel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
