-- MySQL Script generated by MySQL Workbench
-- MySQL Workbench Forward Engineering
-- Date: Thu Jun 10 11:36:41 2021
-- Model: DB_CWWS.sql    
-- Version: 1.0
-- Author: Gerrit Bohne, Dominik Neddermeyer, Lukas Fladung

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CWWS_25052021
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CWWS_25052021
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CWWS_25052021` DEFAULT CHARACTER SET utf8 ;
USE `CWWS_25052021` ;

-- -----------------------------------------------------
-- Table `CWWS_25052021`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CWWS_25052021`.`User` (
  `User_id` INT NOT NULL AUTO_INCREMENT,
  `User_first_name` VARCHAR(45) NOT NULL,
  `User_second_name` VARCHAR(45) NOT NULL,
  `User_password` VARCHAR(255) NOT NULL,
  `User_email` VARCHAR(45) NOT NULL,
  `User_birthday` DATE NOT NULL,
  PRIMARY KEY (`User_id`),
  UNIQUE INDEX `User_id_UNIQUE` (`User_id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CWWS_25052021`.`Storage_yard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CWWS_25052021`.`Storage_yard` (
  `Storage_id` INT NOT NULL AUTO_INCREMENT,
  `Storage_name` VARCHAR(45) NOT NULL,
  `Storage_description` VARCHAR(45) NULL,
  `Storage_category` VARCHAR(45) NOT NULL,
  `Storage_picture` BLOB NOT NULL,
  `Storage_format_heigth` FLOAT NOT NULL,
  `Storage_format_width` FLOAT NOT NULL,
  `Storage_format_length` FLOAT NOT NULL,
  `Storage_furniture` VARCHAR(45) NOT NULL,
  `User_User_id1` INT NOT NULL,
  PRIMARY KEY (`Storage_id`),
  UNIQUE INDEX `Storage_id_UNIQUE` (`Storage_id` ASC) ,
  INDEX `fk_Storage_yard_User1_idx` (`User_User_id1` ASC) ,
  CONSTRAINT `fk_Storage_yard_User1`
    FOREIGN KEY (`User_User_id1`)
    REFERENCES `CWWS_25052021`.`User` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CWWS_25052021`.`Substorage_yard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CWWS_25052021`.`Substorage_yard` (
  `Substorage_id` INT NOT NULL AUTO_INCREMENT,
  `Substorage_name` VARCHAR(45) NOT NULL,
  `Substorage_describtion` VARCHAR(45) NOT NULL,
  `Substorage_picture` BLOB NULL,
  `Storage_yard_Storage_id` INT NOT NULL,
  PRIMARY KEY (`Substorage_id`),
  UNIQUE INDEX `Substorage_id_UNIQUE` (`Substorage_id` ASC) ,
  INDEX `fk_Substorage_yard_Storage_yard1_idx` (`Storage_yard_Storage_id` ASC) ,
  CONSTRAINT `fk_Substorage_yard_Storage_yard1`
    FOREIGN KEY (`Storage_yard_Storage_id`)
    REFERENCES `CWWS_25052021`.`Storage_yard` (`Storage_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CWWS_25052021`.`Articel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CWWS_25052021`.`Articel` (
  `Articel_id` INT NOT NULL AUTO_INCREMENT,
  `Articel_name` VARCHAR(45) NOT NULL,
  `Articel_format` VARCHAR(45) NOT NULL,
  `Articel_picture` BLOB NOT NULL,
  `Articel_description` VARCHAR(45) NOT NULL,
  `Articel_alias` VARCHAR(45) NOT NULL,
  `Articel_expiry` DATE NOT NULL,
  `User_User_id1` INT NOT NULL,
  PRIMARY KEY (`Articel_id`),
  UNIQUE INDEX `Articel_id_UNIQUE` (`Articel_id` ASC) ,
  INDEX `fk_Articel_User1_idx` (`User_User_id1` ASC) ,
  CONSTRAINT `fk_Articel_User1`
    FOREIGN KEY (`User_User_id1`)
    REFERENCES `CWWS_25052021`.`User` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CWWS_25052021`.`Subarticel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CWWS_25052021`.`Subarticel` (
  `Subarticel_id` INT NOT NULL AUTO_INCREMENT,
  `Subarticel_name` VARCHAR(45) NOT NULL,
  `Subarticel_format` VARCHAR(45) NOT NULL,
  `Subarticel_picture` BLOB NOT NULL,
  `Subarticel_description` VARCHAR(45) NOT NULL,
  `Subarticel_alias` VARCHAR(45) NOT NULL,
  `Subarticel_expiry` DATE NOT NULL,
  `Subarticel_time_of_storage` DATETIME NOT NULL,
  `Subarticel_quantity` INT NULL,
  `Articel_Articel_id1` INT NOT NULL,
  `Articel_User_User_id1` INT NOT NULL,
  PRIMARY KEY (`Subarticel_id`),
  UNIQUE INDEX `Subarticel_id_UNIQUE` (`Subarticel_id` ASC) ,
  INDEX `fk_Subarticel_Articel1_idx` (`Articel_Articel_id1` ASC, `Articel_User_User_id1` ASC) ,
  CONSTRAINT `fk_Subarticel_Articel1`
    FOREIGN KEY (`Articel_Articel_id1`)
    REFERENCES `CWWS_25052021`.`Articel` (`Articel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CWWS_25052021`.`Substorage_yard_fixed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CWWS_25052021`.`Substorage_yard_fixed` (
  `Substorage_fixed_id` INT NOT NULL AUTO_INCREMENT,
  `Substorage_fixed_name` VARCHAR(45) NOT NULL,
  `Substorage_fixed_describtion` VARCHAR(45) NOT NULL,
  `Substorage_fixed_picture` BLOB NULL,
  `Substorage_fixed_volume` INT NULL,
  `Substorage_yard_Substorage_id` INT NOT NULL,
  `Subarticel_Subarticel_id` INT NOT NULL,
  PRIMARY KEY (`Substorage_fixed_id`),
  UNIQUE INDEX `Substorage_fixed_id_UNIQUE` (`Substorage_fixed_id` ASC) ,
  INDEX `fk_Substorage_yard_fixed_Substorage_yard1_idx` (`Substorage_yard_Substorage_id` ASC) ,
  INDEX `fk_Substorage_yard_fixed_Subarticel1_idx` (`Subarticel_Subarticel_id` ASC) ,
  CONSTRAINT `fk_Substorage_yard_fixed_Substorage_yard1`
    FOREIGN KEY (`Substorage_yard_Substorage_id`)
    REFERENCES `CWWS_25052021`.`Substorage_yard` (`Substorage_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Substorage_yard_fixed_Subarticel1`
    FOREIGN KEY (`Subarticel_Subarticel_id`)
    REFERENCES `CWWS_25052021`.`Subarticel` (`Subarticel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CWWS_25052021`.`Substorage_yard_mobile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CWWS_25052021`.`Substorage_yard_mobile` (
  `Substorage_mobile_id` INT NOT NULL AUTO_INCREMENT,
  `Substorage_mobile_name` VARCHAR(45) NOT NULL,
  `Substorage_mobile_description` VARCHAR(45) NOT NULL,
  `Substorage_mobile_picture` BLOB NULL,
  `Substorage_yard_fixed_Substorage_fixed_id` INT NOT NULL,
  `Subarticel_Subarticel_id` INT NOT NULL,
  PRIMARY KEY (`Substorage_mobile_id`),
  UNIQUE INDEX `Substorage_mobile_id_UNIQUE` (`Substorage_mobile_id` ASC) ,
  INDEX `fk_Substorage_yard_mobile_Substorage_yard_fixed1_idx` (`Substorage_yard_fixed_Substorage_fixed_id` ASC) ,
  INDEX `fk_Substorage_yard_mobile_Subarticel1_idx` (`Subarticel_Subarticel_id` ASC) ,
  CONSTRAINT `fk_Substorage_yard_mobile_Substorage_yard_fixed1`
    FOREIGN KEY (`Substorage_yard_fixed_Substorage_fixed_id`)
    REFERENCES `CWWS_25052021`.`Substorage_yard_fixed` (`Substorage_fixed_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Substorage_yard_mobile_Subarticel1`
    FOREIGN KEY (`Subarticel_Subarticel_id`)
    REFERENCES `CWWS_25052021`.`Subarticel` (`Subarticel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
