-- MySQL Script generated by MySQL Workbench
-- Fri Jun 18 18:24:03 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CWWS_25052021
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema CWWS_25052021
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CWWS_25052021` DEFAULT CHARACTER SET utf8 ;
USE `CWWS_25052021` ;

-- -----------------------------------------------------
-- Table `CWWS_25052021`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CWWS_25052021`.`User` (
  `User_id` INT NOT NULL AUTO_INCREMENT,
  `User_name` VARCHAR(45) NOT NULL,
  `User_password` VARCHAR(255) NOT NULL,
  `User_email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`User_id`),
  UNIQUE INDEX `User_id_UNIQUE` (`User_id` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CWWS_25052021`.`Substorage_yard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CWWS_25052021`.`Substorage_yard` (
  `Substorage_id` INT NOT NULL AUTO_INCREMENT,
  `Storage_yard_Storage_id` INT NOT NULL,
  `Substorage_quantity` INT NOT NULL,
  PRIMARY KEY (`Substorage_id`),
  INDEX `fk_Substorage_yard_Storage_yard1_idx` (`Storage_yard_Storage_id` ASC) ,
  CONSTRAINT `fk_Substorage_yard_Storage_yard1`
    FOREIGN KEY (`Storage_yard_Storage_id`)
    REFERENCES `CWWS_25052021`.`Storage_yard` (`Storage_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CWWS_25052021`.`Usage_statistics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CWWS_25052021`.`Usage_statistics` (
  `idUsage_statistics` INT NOT NULL AUTO_INCREMENT,
  `Usage_statistics_number_of_accesses` INT UNSIGNED NULL,
  `Usage_statistics_last_modified` DATETIME NULL,
  PRIMARY KEY (`idUsage_statistics`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CWWS_25052021`.`Articel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CWWS_25052021`.`Articel` (
  `Articel_id` INT NOT NULL AUTO_INCREMENT,
  `Articel_expiry` DATE NULL,
  `Articel_picture` BLOB NOT NULL,
  `Articel_rotatable` TINYINT(1) NULL,
  `Articel_stackable` TINYINT(1) NULL,
  `Articel_binding` TINYINT(1) NULL,
  `Articel_extracted` TINYINT(1) NULL,
  `Articel_group_Articel_group_id` INT NOT NULL,
  `Usage_statistics_idUsage_statistics` INT NOT NULL,
  `Articel_time_of_storage` DATE NOT NULL,
  `Properties_Properties_id` INT NOT NULL,
  PRIMARY KEY (`Articel_id`),
  UNIQUE INDEX `Articel_id_UNIQUE` (`Articel_id` ASC) ,
  INDEX `fk_Articel_Articel_group1_idx` (`Articel_group_Articel_group_id` ASC) ,
  INDEX `fk_Articel_Usage_statistics1_idx` (`Usage_statistics_idUsage_statistics` ASC) ,
  INDEX `fk_Articel_Properties1_idx` (`Properties_Properties_id` ASC) ,
  CONSTRAINT `fk_Articel_Articel_group1`
    FOREIGN KEY (`Articel_group_Articel_group_id`)
    REFERENCES `CWWS_25052021`.`Articel_group` (`Articel_group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articel_Usage_statistics1`
    FOREIGN KEY (`Usage_statistics_idUsage_statistics`)
    REFERENCES `CWWS_25052021`.`Usage_statistics` (`idUsage_statistics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articel_Properties1`
    FOREIGN KEY (`Properties_Properties_id`)
    REFERENCES `CWWS_25052021`.`Properties` (`Properties_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CWWS_25052021`.`Substorage_yard_mobile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CWWS_25052021`.`Substorage_yard_mobile` (
  `Substorage_mobile_id` INT NOT NULL AUTO_INCREMENT,
  `Substorage_mobile_cover` TINYINT(1) NOT NULL,
  `Substorage_yard_mobile_binding` TINYINT(1) NULL,
  `Substorage_yard_Substorage_id` INT NOT NULL,
  `Properties_Properties_id` INT NOT NULL,
  `Substorage_yard_mobile_Substorage_mobile_id` INT NOT NULL,
  `Format_Format_id` INT NOT NULL,
  `Articel_Articel_id` INT NOT NULL,
  PRIMARY KEY (`Substorage_mobile_id`),
  UNIQUE INDEX `Substorage_mobile_id_UNIQUE` (`Substorage_mobile_id` ASC) ,
  INDEX `fk_Substorage_yard_mobile_Substorage_yard1_idx` (`Substorage_yard_Substorage_id` ASC) ,
  INDEX `fk_Substorage_yard_mobile_Properties1_idx` (`Properties_Properties_id` ASC) ,
  INDEX `fk_Substorage_yard_mobile_Substorage_yard_mobile1_idx` (`Substorage_yard_mobile_Substorage_mobile_id` ASC) ,
  INDEX `fk_Substorage_yard_mobile_Format1_idx` (`Format_Format_id` ASC) ,
  INDEX `fk_Substorage_yard_mobile_Articel1_idx` (`Articel_Articel_id` ASC) ,
  CONSTRAINT `fk_Substorage_yard_mobile_Substorage_yard1`
    FOREIGN KEY (`Substorage_yard_Substorage_id`)
    REFERENCES `CWWS_25052021`.`Substorage_yard` (`Substorage_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Substorage_yard_mobile_Properties1`
    FOREIGN KEY (`Properties_Properties_id`)
    REFERENCES `CWWS_25052021`.`Properties` (`Properties_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Substorage_yard_mobile_Substorage_yard_mobile1`
    FOREIGN KEY (`Substorage_yard_mobile_Substorage_mobile_id`)
    REFERENCES `CWWS_25052021`.`Substorage_yard_mobile` (`Substorage_mobile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Substorage_yard_mobile_Format1`
    FOREIGN KEY (`Format_Format_id`)
    REFERENCES `CWWS_25052021`.`Format` (`Format_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Substorage_yard_mobile_Articel1`
    FOREIGN KEY (`Articel_Articel_id`)
    REFERENCES `CWWS_25052021`.`Articel` (`Articel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CWWS_25052021`.`Substorage_yard_fixed`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CWWS_25052021`.`Substorage_yard_fixed` (
  `Substorage_fixed_id` INT NOT NULL AUTO_INCREMENT,
  `Substorage_yard_mobile_Substorage_mobile_id` INT NOT NULL,
  `Format_Format_id` INT NOT NULL,
  `Articel_Articel_id` INT NOT NULL,
  PRIMARY KEY (`Substorage_fixed_id`),
  INDEX `fk_Substorage_yard_fixed_Substorage_yard_mobile1_idx` (`Substorage_yard_mobile_Substorage_mobile_id` ASC) ,
  INDEX `fk_Substorage_yard_fixed_Format1_idx` (`Format_Format_id` ASC) ,
  INDEX `fk_Substorage_yard_fixed_Articel1_idx` (`Articel_Articel_id` ASC) ,
  CONSTRAINT `fk_Substorage_yard_fixed_Substorage_yard_mobile1`
    FOREIGN KEY (`Substorage_yard_mobile_Substorage_mobile_id`)
    REFERENCES `CWWS_25052021`.`Substorage_yard_mobile` (`Substorage_mobile_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Substorage_yard_fixed_Format1`
    FOREIGN KEY (`Format_Format_id`)
    REFERENCES `CWWS_25052021`.`Format` (`Format_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Substorage_yard_fixed_Articel1`
    FOREIGN KEY (`Articel_Articel_id`)
    REFERENCES `CWWS_25052021`.`Articel` (`Articel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CWWS_25052021`.`Properties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CWWS_25052021`.`Properties` (
  `Properties_id` INT NOT NULL AUTO_INCREMENT,
  `Properties_name` VARCHAR(45) NOT NULL,
  `Properties_description` VARCHAR(45) NULL,
  `Articel_Articel_id` INT NOT NULL,
  `Substorage_yard_Substorage_id` INT NOT NULL,
  `Substorage_yard_fixed_Substorage_fixed_id` INT NOT NULL,
  PRIMARY KEY (`Properties_id`),
  INDEX `fk_Properties_Substorage_yard1_idx` (`Substorage_yard_Substorage_id` ASC) ,
  INDEX `fk_Properties_Substorage_yard_fixed1_idx` (`Substorage_yard_fixed_Substorage_fixed_id` ASC) ,
  CONSTRAINT `fk_Properties_Substorage_yard1`
    FOREIGN KEY (`Substorage_yard_Substorage_id`)
    REFERENCES `CWWS_25052021`.`Substorage_yard` (`Substorage_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Properties_Substorage_yard_fixed1`
    FOREIGN KEY (`Substorage_yard_fixed_Substorage_fixed_id`)
    REFERENCES `CWWS_25052021`.`Substorage_yard_fixed` (`Substorage_fixed_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CWWS_25052021`.`Articel_group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CWWS_25052021`.`Articel_group` (
  `Articel_group_id` INT NOT NULL AUTO_INCREMENT,
  `Articel_group_picture` BLOB NULL,
  `Properties_Properties_id` INT NOT NULL,
  `Usage_statistics_idUsage_statistics` INT NOT NULL,
  `User_User_id` INT NOT NULL,
  PRIMARY KEY (`Articel_group_id`),
  UNIQUE INDEX `Articel_id_UNIQUE` (`Articel_group_id` ASC) ,
  INDEX `fk_Articel_group_Properties1_idx` (`Properties_Properties_id` ASC) ,
  INDEX `fk_Articel_group_Usage_statistics1_idx` (`Usage_statistics_idUsage_statistics` ASC) ,
  INDEX `fk_Articel_group_User1_idx` (`User_User_id` ASC) ,
  CONSTRAINT `fk_Articel_group_Properties1`
    FOREIGN KEY (`Properties_Properties_id`)
    REFERENCES `CWWS_25052021`.`Properties` (`Properties_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articel_group_Usage_statistics1`
    FOREIGN KEY (`Usage_statistics_idUsage_statistics`)
    REFERENCES `CWWS_25052021`.`Usage_statistics` (`idUsage_statistics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Articel_group_User1`
    FOREIGN KEY (`User_User_id`)
    REFERENCES `CWWS_25052021`.`User` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CWWS_25052021`.`Format`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CWWS_25052021`.`Format` (
  `Format_id` INT NOT NULL AUTO_INCREMENT,
  `Format_height` FLOAT NOT NULL,
  `Format_width` FLOAT NOT NULL,
  `Format_length` FLOAT NOT NULL,
  `Format_volume` FLOAT NULL,
  `Articel_group_Articel_group_id` INT NOT NULL,
  PRIMARY KEY (`Format_id`),
  INDEX `fk_Format_Articel_group1_idx` (`Articel_group_Articel_group_id` ASC) ,
  CONSTRAINT `fk_Format_Articel_group1`
    FOREIGN KEY (`Articel_group_Articel_group_id`)
    REFERENCES `CWWS_25052021`.`Articel_group` (`Articel_group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CWWS_25052021`.`Storage_yard`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CWWS_25052021`.`Storage_yard` (
  `Storage_id` INT NOT NULL AUTO_INCREMENT,
  `Storage_category` VARCHAR(45) NOT NULL,
  `User_User_id` INT NOT NULL,
  `Format_Format_id` INT NOT NULL,
  `Properties_Properties_id` INT NOT NULL,
  `Storage_picture` BLOB NOT NULL,
  `Usage_statistics_idUsage_statistics` INT NOT NULL,
  PRIMARY KEY (`Storage_id`),
  UNIQUE INDEX `Storage_id_UNIQUE` (`Storage_id` ASC) ,
  INDEX `fk_Storage_yard_User1_idx` (`User_User_id` ASC) ,
  INDEX `fk_Storage_yard_Format1_idx` (`Format_Format_id` ASC) ,
  INDEX `fk_Storage_yard_Properties1_idx` (`Properties_Properties_id` ASC) ,
  INDEX `fk_Storage_yard_Usage_statistics1_idx` (`Usage_statistics_idUsage_statistics` ASC) ,
  CONSTRAINT `fk_Storage_yard_User1`
    FOREIGN KEY (`User_User_id`)
    REFERENCES `CWWS_25052021`.`User` (`User_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Storage_yard_Format1`
    FOREIGN KEY (`Format_Format_id`)
    REFERENCES `CWWS_25052021`.`Format` (`Format_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Storage_yard_Properties1`
    FOREIGN KEY (`Properties_Properties_id`)
    REFERENCES `CWWS_25052021`.`Properties` (`Properties_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Storage_yard_Usage_statistics1`
    FOREIGN KEY (`Usage_statistics_idUsage_statistics`)
    REFERENCES `CWWS_25052021`.`Usage_statistics` (`idUsage_statistics`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CWWS_25052021`.`Subarticel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CWWS_25052021`.`Subarticel` (
  `Subarticel_id` INT NOT NULL AUTO_INCREMENT,
  `Subarticel_quantity` INT NULL,
  `Articel_Articel_id` INT NOT NULL,
  PRIMARY KEY (`Subarticel_id`),
  UNIQUE INDEX `Subarticel_id_UNIQUE` (`Subarticel_id` ASC) ,
  INDEX `fk_Subarticel_Articel1_idx` (`Articel_Articel_id` ASC) ,
  CONSTRAINT `fk_Subarticel_Articel1`
    FOREIGN KEY (`Articel_Articel_id`)
    REFERENCES `CWWS_25052021`.`Articel` (`Articel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CWWS_25052021`.`Aliase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `CWWS_25052021`.`Aliase` (
  `Aliase_1` VARCHAR(45) NOT NULL,
  `Articel_Articel_id` INT NOT NULL,
  PRIMARY KEY (`Aliase_1`),
  INDEX `fk_Aliase_Articel1_idx` (`Articel_Articel_id` ASC) ,
  CONSTRAINT `fk_Aliase_Articel1`
    FOREIGN KEY (`Articel_Articel_id`)
    REFERENCES `CWWS_25052021`.`Articel` (`Articel_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
